version: '2'

networks:
  backend:

services:
  app:
    build:
      context: .
      dockerfile: ./php.Dockerfile
    ports:
      - 80
    volumes:
      - .:/data
    command: php -S 0.0.0.0:80 /data/index.php
    networks:
      - backend
    depends_on:
      - redis
    links:
       - redis:redis
    environment:
      - "HOST_IP=10.211.55.12" # Replace with docker-machine ip

  redis:
    image: redis:3.0-alpine
    networks:
      - backend

  gobetween:
    image: yyyar/gobetween
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - "./gobetween/conf:/etc/gobetween/conf/:rw"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - backend