################################################################
# Global configuration
################################################################
port = ":80"
defaultEntryPoints = ["http"]
logLevel = "DEBUG"
debug = true

################################################################
# Web configuration backend
################################################################

[web]
address = ":8080"

################################################################
# Docker configuration backend
################################################################

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "local.docker"
watch = true
